[package]
name = "aurelius"
version = "0.2.0"
authors = ["Andy Russell <arussell123@gmail.com>"]
description = "A complete solution for previewing markdown."
documentation = "https://euclio.github.io/aurelius"
homepage = "https://github.com/euclio/aurelius"
repository = "https://github.com/euclio/aurelius"
readme = "README.md"
keywords = ["markdown", "vim"]
license = "MIT/Apache-2.0"

[dependencies]
chan = "0.1.14"
handlebars = "0.25"
handlebars-iron = { version = "0.23", features = ["serde_type"] }
iron = "0.5"
lazy_static = "0.2"
log = "0.3.1"
mount = "0.3"
porthole = "0.1.0"
pulldown-cmark = { version = "0.0.14", default-features = false }
serde = "0.9"
serde_json = "0.9"
staticfile = "0.4"
url = "1.1.0"
websocket = { version = "0.19", default-features = false }

[dev-dependencies]
reqwest = "0.5"
iron-test = "0.5"
