[package]
name = "aurelius"
version = "0.1.3"
authors = ["Andy Russell <arussell123@gmail.com>"]
description = "A complete solution for previewing markdown."

documentation = "https://euclio.github.io/aurelius"
homepage = "https://github.com/euclio/aurelius"
repository = "https://github.com/euclio/aurelius"
readme = "README.md"

keywords = ["markdown", "vim"]
license = "MIT"

[dependencies]
hoedown = "3.0.2"
log = "0.3.1"
nickel = "0.7.0"
url = "0.2.36"
uuid = "0.1.17"
websocket = "~0.13.1"
