[package]
name = "aurelius"
version = "0.1.7"
authors = ["Andy Russell <arussell123@gmail.com>"]
description = "A complete solution for previewing markdown."

documentation = "https://euclio.github.io/aurelius"
homepage = "https://github.com/euclio/aurelius"
repository = "https://github.com/euclio/aurelius"
readme = "README.md"

keywords = ["markdown", "vim"]
license = "MIT"

[dependencies]
chan = "0.1.14"
hoedown = "3.0.2"
log = "0.3.1"
nickel = "0.7.0"
porthole = "0.1.0"
url = "0.5.0"
websocket = "~0.15.0"
